### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by tiagomaricate** [iarthstar/copy-paste-shadows#3]
After copy a shadow and select another element to past it, I receive the message "Something went wrong..."

**Comment by iarthstar** [comment]
Hey @tiagomaricate, I just tried the Copying and Pasting Shadows works perfectly fine for me...please check the below attachment


https://user-images.githubusercontent.com/14848544/102905498-4304b880-4499-11eb-8656-46f05241f8ce.mp4

What I would suggest, you to share your screen recording with below steps:

1) Open MacOS Search, type in "Console", Open Console App.
2) In Console App's search box type in "Sketch".
3) Now try performing shadows actions, logs will show up in Console App.

By this I will be able to understand the issue and help you out...

**Comment by tiagomaricate** [comment]
> Hey @tiagomaricate, I just tried the Copying and Pasting Shadows works perfectly fine for me...please check the below attachment
> 
>  Screen.Recording.2020-12-22.at.8.55.35.PM.1.mp4 
> 
> What I would suggest, you to share your screen recording with below steps:
> 
> 1. Open MacOS Search, type in "Console", Open Console App.
> 2. In Console App's search box type in "Sketch".
> 3. Now try performing shadows actions, logs will show up in Console App.
> 
> By this I will be able to understand the issue and help you out...

It was a problem with Sketch (so surprise).
Now it's working perfectly!

Thank you very much!
